name: Auction Calendar

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:

  update_auctions:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2 
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  

    - name: Install node and dependencies
      run: |
        npm install
        
    - name: Download new data and update CSVs
      env:
        BRIGHTDATA_AUTH: ${{ secrets.BRIGHTDATA_AUTH }}
      run: |
        node scrapers/calendar.js

    - name: Commit changes
      uses: ./.github/workflows/commit_changes.yml
      with:
        message: "Latest auction schedule" 

  push-static-pages:
    needs: update_auctions
    uses: ./.github/workflows/static.yml
        
