name: Download New Filings

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:

  update_auctions:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2 
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  

    - name: Install node and dependencies
      run: |
        npm install
        
    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
          version: '1.10'
          
    - name: Install julia dependencies
      run: |
          julia -e 'using Pkg; Pkg.add("DataFrames")'
          julia -e 'using Pkg; Pkg.add("CSV")'
          julia -e 'using Pkg; Pkg.add("ProgressMeter")'
          
    - name: Process auctions
      env:
        BRIGHTDATA_AUTH: ${{ secrets.BRIGHTDATA_AUTH }}
      run: |
        julia scrapers/download_case_filings.jl

    - name: Commit changes
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git add .
        git commit -m "Latest auction schedule" || echo "No changes to commit"
        git push

  push-static-pages:
    needs: update_auctions
    uses: ./.github/workflows/static.yml
        
