# .github/workflows/commit_changes.yml
name: Commit Changes

on:
  workflow_call:
    inputs:
      message:
        description: 'Commit message'
        required: true
        type: string

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Commit changes
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git fetch origin
        git rebase origin/master
        git add .
        git commit -m "${{ inputs.message }}" || echo "No changes to commit"
        git push --force-with-lease