name: Daily Auction Update

on:
  workflow_dispatch:

jobs:

  update_auctions:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  

    - name: Install python dependencies
      run: |
        sudo apt-get install tesseract-ocr libtesseract-dev poppler-utils graphicsmagick -y
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install node and dependencies
      run: |
        npm install
        
    - name: Download new data and update CSVs
      env:
        BRIGHTDATA_AUTH: ${{ secrets.BRIGHTDATA_AUTH }}
      run: |
        node scrapers/brooklyn.js
        python -u scrapers/manhattan.py

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
          version: '1.9'
          
    - name: Install julia dependencies
      run: |
          julia --project=. -e 'using Pkg; Pkg.instantiate()'
          
    - name: Process auctions
      run: |
        # Check if new files are created
        if [[ `git status --porcelain` ]]; then
          git status
          julia --project=. process_auctions.jl
        else
          echo "No new files created"
        fi

    - name: Commit changes
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git add .
        git commit -m "Latest auction schedule" || echo "No changes to commit"
        git push

  push-static-pages:
    needs: update_auctions
    uses: ./.github/workflows/static.yml
        
