name: Daily Sales Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 every day
  workflow_dispatch:

jobs:

  update_sales:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'
        
    - name: Install dependencies
      run: |
        julia -e 'using Pkg; Pkg.add("XLSX")'
        julia -e 'using Pkg; Pkg.add("DataFrames")'
        julia -e 'using Pkg; Pkg.add("CSV")'
        
    - name: Download new data and update CSVs
      run: |
        julia nyc_data.jl

    - name: Check for changes
      run: |
        if ! git diff --exit-code; then
          echo "No changes to commit"
          exit 0
        fi
        
    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add manhattan.csv
        git commit -m "Daily update to manhattan.csv"
        git push