name: Daily Sales Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 every day

jobs:

  update_sales:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'
        
    - name: Install Dependencies
      run: julia -e 'import Pkg; Pkg.instantiate()'
        
    - name: Download new data and update CSVs
      run: |
        julia nyc_data.jl
        
    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add manhattan.csv
        git commit -m "Daily update to manhattan.csv"
        git push